spring:
  profiles:
    active: dev
    include: private

  thymeleaf:
    cache: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      suffix: .html

swzl:
  thread:
    core-pool-size: 10
    maximum-pool-size: 20
    keep-alive-time: 50
    queue-size: 10000


