spring:
  application:
    name: swzl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swzl?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: heheda123456
    type: com.alibaba.druid.pool.DruidDataSource

    #   数据源其他配置
    druid:
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
        url-pattern: '/druid/*'
        login-username: 'violet-eve-garden'
        login-password: 'Zxzuishuaiaaa049'
        reset-enable: false

  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss  # 统一日期转换格式

  redis:
    host: localhost
    port: 6379
    database: 0
    username: default
    password: heheda123456

  file:
    path: /usr/local/mydata/swzl/logs/prod
    name: swzl-prod.log

file:
  upload_path: /usr/local/mydata/swzl/files/upload

mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations:
    - classpath:mybatis/mappers/*.xml

server:
  port: 8081